"
" dotphiles : https://github.com/dotphiles/dotphiles
"
" Setup vim and load required plugins before dotvim
"
" Authors:
"   Ben O'Hara <bohara@gmail.com>
"

" Call dotvim
source ~/.vim/dotvim.vim

if has("user_commands")
  set nocompatible
  filetype off
  set rtp+=~/.vim/bundle/vundle/
  call vundle#rc()
  "let g:vundles=['general', 'programming', 'php', 'ruby', 'python', 'javascript', 'html', 'misc']
  let g:vundles=['general', 'programming']
  let g:neocomplcache_enable_at_startup = 1
  " Tell Neosnippet about the other snippets
  let g:neosnippet#snippets_directory='~/.vim/bundle/snipmate-snippets/snippets'
  " Load 'vundles'
  source ~/.vim/vundles.vim
  " Add extra bundles here...
  " Bundle 'reponame'
endif

" Customize to your needs...
Bundle 'hynek/vim-python-pep8-indent'
Bundle 'yodiaditya/vim-pydjango'
let g:syntastic_python_flake8_args='--ignore=E501'

autocmd BufRead,BufNewFile /data/rancid/configs/* set syntax=cisco
autocmd BufRead,BufNewFile /opt/tftpboot/acl/* set syntax=cisco
Bundle 'benohara/cisco.vim'
Bundle 'mkitt/tabline.vim'
