# If you come from bash you might have to change your $PATH.
export PATH=$HOME/.bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
#ZSH Custom path
ZSH_CUSTOM=$HOME/.zsh_custom
AWS_DEFAULT_PROFILE=default
# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
#ZSH_THEME="powerlevel9k/powerlevel9k"


POWERLEVEL9K_MODE='nerdfont-complete'
ZSH_THEME="powerlevel9k/powerlevel9k"

custom_spotify () {
#    local color='%F{cyan}'
  state=`osascript -e 'tell application "Spotify" to player state as string'`;
  if [ $state = "playing" ]; then
    artist=`osascript -e 'tell application "Spotify" to artist of current track as string'`;
    track=`osascript -e 'tell application "Spotify" to name of current track as string'`;

      echo -n "\uf485 $artist - $track " ; 

  fi
}

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="dd.mm.yyyy"

# Would you like to use another custom folder than $ZSH/custom?

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(zsh-autosuggestions git colorize aws brew cask pip vagrant cp screen osx tugboat go github docker gitignore themes)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
export EDITOR='subl -w '

alias next="spotify next"
alias play="spotify play"
alias pause="spotify pause"
alias prev="spotify prev"


# This adds zsh completion for AWS CLI 
if [ -f /usr/bin/aws_zsh_completer.sh ];then 
  source '/usr/bin/aws_zsh_completer.sh'
fi

# And For Mac
if [ -f /usr/local/bin/aws_zsh_completer.sh ];then
  source '/usr/local/bin/aws_zsh_completer.sh'
fi

source ~/.iterm2_shell_integration.`basename $SHELL`


#Powerline 9k stuff



## POWERLEVEL9K PROMT SETTINGS ##
PPOWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{cyan}\u256D\u2500%f"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{014}\u2570%F{cyan}\uF460%F{073}\uF460%F{109}\uF460%f "
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_to_unique"
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon status kubecontext aws dir_writable dir vcs)
#POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(icons_test)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(custom_spotify command_execution_time background_jobs ssh battery time history)
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
## MISC ##
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_STATUS_OK_IN_NON_VERBOSE=true



###### LEFT SIDE ######
## OS Icon
POWERLEVEL9K_OS_ICON_BACKGROUND="black"
POWERLEVEL9K_OS_ICON_FOREGROUND="cyan"

## Status
POWERLEVEL9K_STATUS_OK_BACKGROUND="black"
POWERLEVEL9K_STATUS_OK_FOREGROUND="cyan"
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="black"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="red"

## Kubecontext
POWERLEVEL9K_KUBECONTEXT_FOREGROUND="cyan"
POWERLEVEL9K_KUBECONTEXT_BACKGROUND="black"

## AWS
POWERLEVEL9K_AWS_FOREGROUND="cyan"
POWERLEVEL9K_AWS_BACKGROUND="black"

## Dir Writable
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="cyan"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="black"

## Dir
POWERLEVEL9K_DIR_HOME_BACKGROUND="black"
POWERLEVEL9K_DIR_HOME_FOREGROUND="cyan"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="black"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="cyan"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="black"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="cyan"


## VCS
POWERLEVEL9K_VCS_CLEAN_BACKGROUND="black"
POWERLEVEL9K_VCS_CLEAN_FOREGROUND="cyan"
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="black"
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="yellow"
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="black"
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="yellow"
POWERLEVEL9K_VCS_GIT_GITHUB_ICON="\ue709"
POWERLEVEL9K_VCS_GIT_BITBUCKET_ICON="\ue703"
POWERLEVEL9K_VCS_GIT_GITLAB_ICON="\ue705"
POWERLEVEL9K_VCS_GIT_ICON=""



###### RIGHT SIDE

## Spotify
POWERLEVEL9K_CUSTOM_SPOTIFY_FOREGROUND="cyan"
POWERLEVEL9K_CUSTOM_SPOTIFY_BACKGROUND="black"
POWERLEVEL9K_CUSTOM_SPOTIFY="custom_spotify"

## Command Execution TIme
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND="black"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND="cyan"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_ICON="\u231A"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD="0"



## Background Jobs
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND="black"
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND="cyan"


##Ssh
#POWERLEVEL9K_SSH_FOREGROUND="226"
POWERLEVEL9K_SSH_FOREGROUND="black"
POWERLEVEL9K_SSH_BACKGROUND="cyan"
POWERLEVEL9K_SSH_ICON="\uF489"  #

##Battery 
POWERLEVEL9K_BATTERY_CHARGING="yellow"
POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND="yellow"
POWERLEVEL9K_BATTERY_CHARGED="cyan"
POWERLEVEL9K_BATTERY_CHARGED_FOREGROUND="cyan"
POWERLEVEL9K_BATTERY_DISCONNECTED="cyan"
POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND="cyan"
POWERLEVEL9K_BATTERY_LOW_THRESHOLD="15"
POWERLEVEL9K_BATTERY_LOW_COLOR="red"
POWERLEVEL9K_BATTERY_VERBOSE="flase"

##Time
POWERLEVEL9K_TIME_FORMAT="%D{\uf017 %T}"
POWERLEVEL9K_TIME_FOREGROUND="cyan"
POWERLEVEL9K_TIME_BACKGROUND="black"

##History
POWERLEVEL9K_HISTORY_FOREGROUND="cyan"
POWERLEVEL9K_HISTORY_BACKGROUND="black"

##Misc
# POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND="235"
# POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND="red"
# POWERLEVEL9K_USER_DEFAULT_BACKGROUND="235"
# POWERLEVEL9K_USER_DEFAULT_FOREGROUND="cyan"
# POWERLEVEL9K_USER_ROOT_BACKGROUND="235"
# POWERLEVEL9K_USER_ROOT_FOREGROUND="red"
# POWERLEVEL9K_USER_ICON="\uF415" #
# POWERLEVEL9K_ROOT_ICON="\u26A1" # ⚡
# POWERLEVEL9K_HOST_LOCAL_BACKGROUND="235"
# POWERLEVEL9K_HOST_LOCAL_FOREGROUND="cyan"
# POWERLEVEL9K_HOST_REMOTE_BACKGROUND="235"
# POWERLEVEL9K_HOST_REMOTE_FOREGROUND="cyan"
# POWERLEVEL9K_HOST_ICON="\uF109" #
# POWERLEVEL9K_HOST_ICON_FOREGROUND="red"
# POWERLEVEL9K_HOST_ICON_BACKGROUND="black"