## My custom Vars
POWERLEVEL9K_MODE='nerdfont-complete'

#Export for personal Binarys
export PATH=$HOME/.bin:/usr/local/bin:$PATH
export GPG_TTY=$(tty)

GENCOMPL_FPATH=$HOME/.zsh-completions
#zsh-completions
fpath=(/usr/local/share/zsh-completions $GENCOMPL_FPATH $fpath)

## Antigen
source $HOME/.antigen/antigen.zsh

##Antigen configuration
antigen use oh-my-zsh

## Always Bundles
antigen bundles <<EOBUNDLE
  zsh-users/zsh-syntax-highlighting
  zsh-users/zsh-autosuggestions
  desyncr/auto-ls
  colorize
  unixorn/autoupdate-antigen.zshplugin

EOBUNDLE

## Darwin Bundles
if [[ $(uname) = "Darwin" ]]; then
  antigen bundles <<EOMAC
    brew
    osx
EOMAC
fi

if [[ $(hash git) ]]; then
  antigen bundles <<EOBUNDLE
  git
  zsh-users/zsh-completions
  caarlos0/zsh-open-pr
  peterhurford/git-it-on.zsh
EOBUNDLE
fi


## Docker Bundles
if [[ $(hash docker) ]]; then
  antigen bundle docker
fi


##Themeing for Antigen
antigen theme bhilburn/powerlevel9k powerlevel9k
#antigen theme iam4x/zsh-iterm-touchbar

##Apply antigen Configuration
antigen apply


## Local Function for Shspotify
if [[ $(uname) = "Darwin" ]]; then
  custom_spotify () {
  #    local color='%F{cyan}'
    state=`osascript -e 'tell application "Spotify" to player state as string'`;
    if [ $state = "playing" ]; then
      artist=`osascript -e 'tell application "Spotify" to artist of current track as string'`;
      track=`osascript -e 'tell application "Spotify" to name of current track as string'`;
      echo -n "\uf485 $artist - $track " ;
    fi
  }

## Alias List
alias next="spotify next"
alias play="spotify play"
alias pause="spotify pause"
alias prev="spotify prev"
alias mac-update="brew update && brew upgrade && brew cu -y && antigen update && antigen reset && mas upgrade && dotsync -U && dotsync -P"
else
  custom_spotify() { true;}
fi


##Set Editor for both ssh and Loal sessions
if [[ -n $SSH_CONNECTION ]]; then
    export EDITOR='vim'
else
    export EDITOR='atom -w '
fi


# And For Mac iTerm2 intigration
if [[ $(uname) = "Darwin" ]]; then
  # iTerm2 Shell integration
  source ~/.iterm2_shell_integration.`basename $SHELL`
fi

if [[ $(type gcloud) && $(uname) = "Darwin" ]]; then
  echo "sdk should load"
  source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
  source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'
fi


## POWERLEVEL9K PROMT SETTINGS ##
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{cyan}\u256D\u2500%f"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{014}\u2570%F{cyan}\uF460%F{073}\uF460%F{109}\uF460%f "
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_to_unique"
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon status kubecontext dir_writable dir vcs)
#POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(icons_test)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(custom_spotify command_execution_time background_jobs battery time ssh context_joined)
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
## MISC ##
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_STATUS_OK_IN_NON_VERBOSE=true



###### LEFT SIDE ######
## OS Icon
POWERLEVEL9K_OS_ICON_BACKGROUND="black"
POWERLEVEL9K_OS_ICON_FOREGROUND="cyan"

## Status
POWERLEVEL9K_STATUS_OK_BACKGROUND="black"
POWERLEVEL9K_STATUS_OK_FOREGROUND="cyan"
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="black"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="red"

## Kubecontext
POWERLEVEL9K_KUBECONTEXT_FOREGROUND="cyan"
POWERLEVEL9K_KUBECONTEXT_BACKGROUND="black"

## Dir Writable
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="cyan"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="black"

## Dir
POWERLEVEL9K_DIR_HOME_BACKGROUND="black"
POWERLEVEL9K_DIR_HOME_FOREGROUND="cyan"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="black"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="cyan"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="black"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="cyan"


## VCS
POWERLEVEL9K_VCS_CLEAN_BACKGROUND="black"
POWERLEVEL9K_VCS_CLEAN_FOREGROUND="cyan"
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="black"
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="yellow"
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="black"
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="yellow"
POWERLEVEL9K_VCS_GIT_GITHUB_ICON="\ue709"
POWERLEVEL9K_VCS_GIT_BITBUCKET_ICON="\ue703"
POWERLEVEL9K_VCS_GIT_GITLAB_ICON="\ue705"
POWERLEVEL9K_VCS_GIT_ICON=""



###### RIGHT SIDE

## Spotify
POWERLEVEL9K_CUSTOM_SPOTIFY_FOREGROUND="cyan"
POWERLEVEL9K_CUSTOM_SPOTIFY_BACKGROUND="black"
POWERLEVEL9K_CUSTOM_SPOTIFY="custom_spotify"

## Command Execution TIme
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND="black"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND="cyan"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_ICON="\u231A"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD="3"



## Background Jobs
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND="black"
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND="cyan"


##Ssh
#POWERLEVEL9K_SSH_FOREGROUND="226"
POWERLEVEL9K_SSH_FOREGROUND="cyan"
POWERLEVEL9K_SSH_BACKGROUND="black"
POWERLEVEL9K_SSH_ICON="\uF489"  #

##Battery
POWERLEVEL9K_BATTERY_CHARGING="yellow"
POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND="yellow"
POWERLEVEL9K_BATTERY_CHARGED="cyan"
POWERLEVEL9K_BATTERY_CHARGED_FOREGROUND="cyan"
POWERLEVEL9K_BATTERY_DISCONNECTED="cyan"
POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND="cyan"
POWERLEVEL9K_BATTERY_LOW_THRESHOLD="15"
POWERLEVEL9K_BATTERY_LOW_COLOR="red"
POWERLEVEL9K_BATTERY_VERBOSE="flase"

##Time
POWERLEVEL9K_TIME_FORMAT="%D{\uf017 %T}"
POWERLEVEL9K_TIME_FOREGROUND="cyan"
POWERLEVEL9K_TIME_BACKGROUND="black"

##Context
DEFAULT_USER=lonix
POWERLEVEL9K_ALWAYS_SHOW_CONTEXT=false #Always show this segment, including $USER and hostname.
POWERLEVEL9K_ALWAYS_SHOW_USER=false #Always show the username, but conditionalize the hostname.
POWERLEVEL9K_CONTEXT_TEMPLATE="%n@%m"
POWERLEVEL9K_CONTEXT_BACKGROUND="black"
POWERLEVEL9K_CONTEXT_FOREGROUND="cyan"
